### ISSUE TITLE
Error: target must be a playlist when dragging

### ISSUE THREAD

**Issue by Turqueso** [Mallander/playlist-enhancer#5] opened 2021-06-26 17:31 UTC
Foundry 0.8.7
system DnD5e

When I try to drag a song to another playlist I get the error "the target must be a playlist"

**Comment by Mallander** [comment] 2021-06-26 17:43
Thanks for raising, I'll take a look and fix in the next update

**Comment by Mallander** [comment] 2021-06-26 17:54
If possible, would you be able to record this happening and send me a video? (GIF etc is also fine too)

It will help massively with the investigation.

**Comment by Mallander** [comment] 2021-06-27 17:14
Hi @Turqueso,

I've not been able to replicate this error myself (Fresh install, 0.8.7 DnD5e), so I'm going to add some extra error wording and debug in the next release to help narrow down where/why this is happening for you.

Hopefully that should let us find out the cause.

**Comment by Mallander** [comment] 2021-07-02 21:24
Latest release has just gone out. I couldn't replicate any bug that caused this behaviour so I've updated my error messaging to hopefully dig deeper into the issue.

Please could you let me know whether the error still occurs and what error messages you're now seeing?

**Comment by Turqueso** [comment] 2021-07-05 17:49
I tired again and same issue

Details
foundry 0.8.8
playlist enhancer 1.1.1
Firefox 89.0.2 (tested on mac and windows)

Steps
- New world. Activate playlist enhancer. No other modules.
- Creat 2 playlist, add a song to each
- Drag and drop song to the other playlist
- getting this error:
![imagen](https://user-images.githubusercontent.com/4932347/124505130-16095a80-dd86-11eb-9691-de3c83e98094.png)
- Console log:
![imagen](https://user-images.githubusercontent.com/4932347/124505546-f9215700-dd86-11eb-9950-2647eec2bda1.png)

Am I doing something wrong o is there something else I should do to debug?

**Comment by Mallander** [comment] 2021-07-05 17:53
Thanks for reporting back!

So based on that debug (thanks for sharing it!) it thinks you're dragging the playlist onto the canvas rather than another playlist. Not sure why it would be doing that... a few more questions from me:

- Do you have FVTT in a smaller window, or maximised?
- If you create a Playlist Folder and drag onto there, does the error change?
- Do you have the capability of recording a GIF of you dragging the playlist across just so I can see for myself what actions you're taking?

I'll run some more testing in Firefox myself and see if that's causing the issue.

Thanks!

**Comment by Mallander** [comment] 2021-07-05 17:54
I'll also see if there's a more robust way of doing the entire drag & drop functionality if I can't find anything concrete in the above.

**Comment by Mallander** [comment] 2021-07-05 18:05
Success! It's a firefox bug and I can replicate it!

Will be fixed in the next release.

**Comment by Turqueso** [comment] 2021-07-05 18:39
>     * Do you have FVTT in a smaller window, or maximised?
Maximised firefox window, but i tried to changing sizes with same result. I just tried chrome(on mac) and it works! so is a firefox thing it seems.

>     * If you create a Playlist Folder and drag onto there, does the error change?
Same error.

>     * Do you have the capability of recording a GIF of you dragging the playlist across just so I can see for myself what actions you're taking?
[Webm with a short video](https://drive.google.com/file/d/1iWNTd9tVWyGn8YFvNv1QFe-3CvHbImSc/view?usp=sharing)

**Comment by Mallander** [comment] 2021-07-05 18:47
Thanks for all your help investigating the issue, I've found the problem and am fixing it as we speak!

**Comment by Mallander** [comment] 2021-07-05 19:23
A new release has just been pushed out which should fix this issue. Please let me know if you're still receiving any errors.

**Comment by Turqueso** [comment] 2021-07-05 19:36
It works now! thank you!

**Comment by Mallander** [comment] 2021-07-05 20:20
Awesome, let me konw if you run into any other issues!

**Closed by Mallander** 2021-07-05 20:20 UTC
Labels: bug
